### ISSUE TITLE
More Evil

### ISSUE THREAD

**Issue by massierick** [toddlyons/evil-plans#2]
Perhaps I may suggest spending some time listening to Ziltoid the Omniscient (see my avatar)? His evil ways will surely guide you on you path. If you are of an open musical mind, and enjoy coffee, aliens, and weirdness, Devin Townsend's two Ziltoid albums will surely serve as a proper training ground for your aspirations. 

Sorry, just had to comment on this repo, lol....

**Comment by toddlyons** [comment]
Good tip, Rick. Added to my list.
